server:
  port: 1111
spring:
  application:
    name: TRAIN-SERVICE
  data:
    mongodb:
      uri: mongodb+srv://ujjwal:ujjwal@cluster0.78cjd.mongodb.net/test
eureka:
  client:
    register-with-eureka: true
    fetch-registry: true
    service-url:
      defaultZone: http://localhost:8761/eureka/
  instance:
    hostname: localhost